name: Ping Streamlit App Daily

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit App
        run: curl -s https://platformdata.streamlit.app || echo "Ping failed"
